fn yellow(text : String) -> String{
  return "\u001b[33m\{text}\u001b[0m".to_string()
}

fn purple(text : String) -> String{
  return "\u001b[35m\{text}\u001b[0m".to_string()
}


fn blue(text : String) -> String{
  return "\u001b[34m\{text}\u001b[0m".to_string()
}


fn red(text : String) -> String{
  return "\u001b[31m\{text}\u001b[0m".to_string()
}

fn orange(text : String) -> String{
  return "\u001b[38;5;208m\{text}\u001b[0m".to_string()
}

fn green(text : String) -> String{
  return "\u001b[32m\{text}\u001b[0m".to_string()
}

fn dark_blue(text : String) -> String{
  return "\u001b[34m\{text}\u001b[0m".to_string()
}